Homework 2
================

### Load packages

``` r
library(tidyverse)
```

## Problem 1

### Import NYC Transit data and perform initial cleaning

``` r
transit_df <- read_csv('data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv',
                       col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>%
  janitor::clean_names() %>%
  select(line:entry, vending, ada) %>%
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

`transit_df` includes variation NYC subway information by station.
Information included includes the subway line that runs through the
station, the station name, latitude and longitude of the station,
various routes served by said station, the type of entrance (stair,
door, easement, elevator, escalator, ramp, walkway), if entrance is
allowed, if station has vending, and if the station is ADA compliant.

We adjusted `Route8`, `Route9`, `Route10`, and `Route11` to character
values. `janitor::clean_names()` adjusted variable names to snake case.
We then selected key variables and adjusted `entry` to a logical
variable. At this stage, the dataset is not yet “tidy” as the route
variables should be in long format.

###### How many distinct stations are there? Note that stations are identified both by name and by line (e.g. 125th St 8th Avenue; 125st Broadway; 125st Lenox); the distinct function may be useful here.

``` r
transit_df %>% 
  select(station_name, line) %>%
  distinct() %>%
  summarize(n = n())
```

    ## # A tibble: 1 × 1
    ##       n
    ##   <int>
    ## 1   465

*There are a total of `465` unique stations in the NYC subway.*

###### How many stations are ADA compliant?

``` r
transit_df %>%
  filter(ada == TRUE) %>%
  select(station_name, line) %>%
  distinct() %>%
  summarize(n = n())
```

    ## # A tibble: 1 × 1
    ##       n
    ##   <int>
    ## 1    84

*`84` unique stations are ADA compliant.*

###### What proportion of station entrances / exits without vending allow entrance?

``` r
transit_df %>%
  filter(vending == "NO") %>%
  group_by(entry) %>%
  summarize(n = n()) %>%
  mutate(prop = n/sum(n))
```

    ## # A tibble: 2 × 3
    ##   entry     n  prop
    ##   <lgl> <int> <dbl>
    ## 1 FALSE   114 0.623
    ## 2 TRUE     69 0.377

*Of station entrances/exits without vending, `37.7%` allow entrance.*

###### Reformat data so that route number and route name are distinct variables. How many distinct stations serve the A train? Of the stations that serve the A train, how many are ADA compliant?

``` r
transit_df %>%
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route"
  ) %>%
  filter(route == "A") %>%
  select(station_name, line) %>%
  distinct() %>%
  summarize(n = n())
```

    ## # A tibble: 1 × 1
    ##       n
    ##   <int>
    ## 1    60

``` r
transit_df %>%
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route"
  ) %>%
  filter(route == "A", ada == TRUE) %>%
  select(station_name, line) %>%
  distinct() %>%
  summarize(n = n())
```

    ## # A tibble: 1 × 1
    ##       n
    ##   <int>
    ## 1    17

*`60` stations serve the A train. Of stations that serve the A train,
`17` stations are ADA compliant.*
